### ISSUE TITLE
Use Default dnsPolicy and dnsConfig when generating manifests

### ISSUE THREAD

**Issue by pgier** [datastax/kaap#117]
Is there a reason why we set non-default dnsConfig values when the migration tool generates manifests?
```
        dnsConfig:
          options:
          - name: ndots
            value: '4'
```
