### ISSUE TITLE
global.tls.functionsWorker.enabled is ignored

### ISSUE THREAD

**Issue by pgier** [datastax/kaap#123]
The functionsWorker tls setting seems to be ignored.  When I have `tls` enabled globally, but disabled on the functionsWorker, then the functionsWorker still gets TLS settings activated.
```
  global:
    tls:
      enabled: true
      functionsWorker:
        enabled: false
```
