### ISSUE TITLE
Proxy configmap is renders with wrong broker urls when cluster.sepc.global.components.brokerBaseName is configured

### ISSUE THREAD

**Issue by MarkusNeuron** [datastax/kaap#160]
By configuring:
```yaml
cluster:
  spec:
    global:
      components: # legacy names to be compatible with existing clusters
        brokerBaseName: neuron-pulsar-broker
```
The service is created correctly:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: dev01-neuron-pulsar-broker
  namespace: dev01-neuron-pulsar
  labels:
    app: pulsar
    cluster: dev01
    component: neuron-pulsar-broker
    resource-set: broker
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
  ...
  ...
  selector:
    app: pulsar
    cluster: dev01
    component: neuron-pulsar-broker
```
but both `dev01-neuron-pulsar-proxy` and `dev01-neuron-pulsar-proxy-ws` contain the wrong broker urls because `broker-` is prefixed but should not be `http://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8080/` instead of correct URL `http://dev01-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8080/`

Proxy config map wrong values `PULSAR_PREFIX_brokerServiceURL, PULSAR_PREFIX_brokerServiceURLTLS, PULSAR_PREFIX_brokerWebServiceURL, PULSAR_PREFIX_brokerWebServiceURLTLS`:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev01-neuron-pulsar-proxy
  namespace: dev01-neuron-pulsar
  labels:
    app: pulsar
    cluster: dev01
    component: neuron-pulsar-proxy
    resource-set: proxy
data:
  PULSAR_PREFIX_numHttpServerThreads: '10'
  PULSAR_PREFIX_tlsHostnameVerificationEnabled: 'false'
  PULSAR_LOG_ROOT_LEVEL: info
  PULSAR_LOG_LEVEL: info
  PULSAR_PREFIX_brokerServiceURL: pulsar://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:6650/
  PULSAR_PREFIX_brokerServiceURLTLS: pulsar+ssl://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:6651/
  PULSAR_PREFIX_brokerWebServiceURL: http://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8080/
  PULSAR_PREFIX_brokerWebServiceURLTLS: https://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8443/
  PULSAR_EXTRA_OPTS: '-Dpulsar.log.root.level=info'
  PULSAR_PREFIX_authenticateMetricsEndpoint: 'false'
  PULSAR_PREFIX_tlsEnabledWithKeyStore: 'false'
  PULSAR_PREFIX_clusterName: dev01
  PULSAR_PREFIX_configurationStoreServers: 'dev01-neuron-pulsar-zookeeper-ca.dev01-neuron-pulsar.svc.cluster.local:2181'
  PULSAR_PREFIX_zookeeperServers: 'dev01-neuron-pulsar-zookeeper-ca.dev01-neuron-pulsar.svc.cluster.local:2181'
  PULSAR_PREFIX_forwardAuthorizationCredentials: 'true'
```

Proxy WS config map wrong values `PULSAR_PREFIX_serviceUrl, PULSAR_PREFIX_serviceUrlTls, PULSAR_PREFIX_brokerServiceUrl, PULSAR_PREFIX_brokerServiceUrlTls`:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev01-neuron-pulsar-proxy-ws
  namespace: dev01-neuron-pulsar
  labels:
    app: pulsar
    cluster: dev01
    component: neuron-pulsar-proxy
    resource-set: proxy
data:
  PULSAR_PREFIX_numHttpServerThreads: '10'
  PULSAR_PREFIX_tlsHostnameVerificationEnabled: 'false'
  PULSAR_LOG_ROOT_LEVEL: info
  PULSAR_PREFIX_serviceUrl: http://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8080/
  PULSAR_PREFIX_serviceUrlTls: https://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:8443/
  PULSAR_PREFIX_brokerServiceUrl: pulsar://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:6650/
  PULSAR_PREFIX_brokerServiceUrlTls: pulsar+ssl://dev01-broker-neuron-pulsar-broker.dev01-neuron-pulsar.svc.cluster.local:6651/
  PULSAR_LOG_LEVEL: info
  PULSAR_PREFIX_webServicePort: '8000'
  PULSAR_PREFIX_zookeeperServers: 'dev01-neuron-pulsar-zookeeper-ca.dev01-neuron-pulsar.svc.cluster.local:2181'
  PULSAR_EXTRA_OPTS: '-Dpulsar.log.root.level=info'
  PULSAR_PREFIX_tlsEnabledWithKeyStore: 'false'
  PULSAR_PREFIX_clusterName: dev01
  PULSAR_PREFIX_configurationStoreServers: 'dev01-neuron-pulsar-zookeeper-ca.dev01-neuron-pulsar.svc.cluster.local:2181'
```
