### ISSUE TITLE
TLS support is not compatible with upstream Pulsar images

### ISSUE THREAD

**Issue by josephglanville** [datastax/kaap#177]
There are a few issues at play here:

1. The `certconverter` routine requires openssl which isn't installed in upstream images
2. `certconverter` also expects to write to `/pulsar` which is not writable by the `pulsar` (uid `10000`) user on the upstream images
3. The TLS configuration for Zookeeper disables support for `TLSv1.3` which is the default on the upstream images.

These can be worked around by crafting a custom image with a Dockerfile like so:
```
FROM apachepulsar/pulsar:3.3.1

USER 0
RUN apk add --no-cache openssl
RUN chown pulsar:root -R /pulsar
USER 10000
```
And then setting these keys on the Zookeeper config:
```
      zookeeper:
        config:
          ssl.protocol: TLSv1.3
          ssl.quorum.protocol: TLSv1.3
          ssl.enabledProtocols: TLSv1.3,TLSv1.2
```
